name: Run test suites and upload coverage reports
on:
  push:
    branches:
      - main
      - beta
jobs:
  runTests:
    name: Run automated tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install packages
        run: npm ci --legacy-peer-deps

      - name: Jest
        run: npm run ci:test

      - name: Storybook CI
        run: |
          chmod +x "./ci-storybook.sh"
          ./ci-storybook.sh
        shell: bash

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./coverage/
          verbose: true
