name: Make new release (latest)
on: workflow_dispatch
jobs:
  createReleasePR:
    name: Create PR for release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main

      - uses: actions/setup-node@v2

      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Install packages
        run: npm ci --legacy-peer-deps

      - name: Get next version
        id: version
        run: |
          next_version=$(npx release-it --release-version)
          echo $next_version
          echo "::set-output name=next::$next_version"

      - name: Get changelog
        id: changelog
        run: |
          changelog=$(npx auto-changelog --stdout --unreleased-only)
          echo $changelog
          echo "::set-output name=changelog::$changelog"

      - name: Stage changes to version, changelog, build
        run: |
          npm run version:latest

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          base: main
          branch: release/latest
          delete-branch: true
          draft: false
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "chore(release): v${{ steps.version.outputs.next }}"
          commit-message: "auto-commit: staged changes"
          labels: release
          body: |
            🤖 **Preparing to release as @latest**

            ${{ steps.changelog.outputs.changelog }}
