name: Make new pre-release (beta)
on: workflow_dispatch
jobs:
  createReleasePR:
    name: Create PR for release
    runs-on: ubuntu-latest

    steps:
      # Setup release branch
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: beta

      - name: Create release branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'release/beta'

      # Push commit from release-it: version bump, changelog, build
      - uses: actions/setup-node@v2

      - name: NPM authentication
        run: npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}

      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Install packages
        run: npm ci --legacy-peer-deps

      - name: Stage changes to version, changelog, build
        run: |
          npm run version:beta

      # Create PR for release branch
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          base: beta
          branch: release/beta
          delete-branch: true
          draft: false
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "chore(release): publish beta"
          commit-message: "auto-commit: staged changes"
          labels: release
          body: |
            🤖 **Preparing to release as @beta**
