name: Make new pre-release (beta)
on: workflow_dispatch
jobs:
  createReleasePR:
    name: Create PR for release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main

      - uses: actions/setup-node@v2

      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Install packages
        run: npm ci --legacy-peer-deps

      - name: Stage changes to version, changelog, build
        run: |
          npm run version:beta

      # https://github.com/peter-evans/create-pull-request#action-outputs
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          branch: release/beta
          delete-branch: true
          draft: false
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "chore(release): publish beta"
          commit-message: "auto-commit: staged changes"
          labels: release
          body: |
            🤖 **Preparing to release as @beta**
